plugins {
    id 'java'
}

group = project.maven_group
version = project.plugin_version

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:${project.paper_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

processResources {
    inputs.property 'version', project.version
    exclude 'assets/pizzarush/**'
    exclude 'assets/modid/**'
    exclude 'data/pizzarush/**'
    filesMatching('paper-plugin.yml') {
        expand version: project.version
    }
}

jar {
    archiveBaseName = 'civ-craft'
}
